In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_csv(r'../../dataset/seattle-weather.csv')

In [3]:
df.head()

         date  precipitation  temp_max  temp_min  wind  weather
0  2012-01-01            0.0      12.8       5.0   4.7  drizzle
1  2012-01-02           10.9      10.6       2.8   4.5     rain
2  2012-01-03            0.8      11.7       7.2   2.3     rain
3  2012-01-04           20.3      12.2       5.6   4.7     rain
4  2012-01-05            1.3       8.9       2.8   6.1     rain

In [4]:
df.tail()

            date  precipitation  temp_max  temp_min  wind weather
1456  2015-12-27            8.6       4.4       1.7   2.9    rain
1457  2015-12-28            1.5       5.0       1.7   1.3    rain
1458  2015-12-29            0.0       7.2       0.6   2.6     fog
1459  2015-12-30            0.0       5.6      -1.0   3.4     sun
1460  2015-12-31            0.0       5.6      -2.1   3.5     sun

In [5]:
df.columns

Index(['date', 'precipitation', 'temp_max', 'temp_min', 'wind', 'weather'], dtype='object')

In [6]:
df.duplicated().sum()

np.int64(0)

In [7]:
df.iloc[:, 2:3]

      temp_max
0         12.8
1         10.6
2         11.7
3         12.2
4          8.9
...        ...
1456       4.4
1457       5.0
1458       7.2
1459       5.6
1460       5.6

[1461 rows x 1 columns]

In [9]:
training_set = df.iloc[:, 2:3].values

In [10]:
len(training_set)

1461

In [ ]:
def df_to_XY(df, window_size = 10):